// Auto-generated by scraper/scrape.py — do not edit by hand.
window.LIVE_DATA = {
  "injuriesByTeam": {
    "Atlanta Dream": "Indya Nivar - Out (Coach's Decision); Brionna Jones - Out (Leg)",
    "Chicago Sky": "Natasha Cloud - Out (Knee); DiJonai Carrington - Out (Foot); Skylar Diggins - Out (Knee); Rickea Jackson - Out (Knee)",
    "Connecticut Sun": "Kennedy Burke - Out (Not Injury Related); Olivia Nelson-Ododa - Out (Knee); Brittney Griner - Out (Knee); Leila Lacan - Out (Not Injury Related)",
    "Dallas Wings": "Christyn Williams - Out (Coach's Decision); Haley Jones - Out (Coach's Decision); Azzi Fudd - Out (Knee); Aziaha James - Out (Leg); Costanza Verona - Out (Personal)",
    "Golden State Valkyries": "Iliana Rupert - Out (Not Injury Related)",
    "Indiana Fever": "Aliyah Boston - Out (Lower Leg)",
    "Las Vegas Aces": "NaLyssa Smith - Out (Leg); Dana Evans - Out (Leg)",
    "Los Angeles Sparks": "Tonie Morgan - Out (Undisclosed); Rae Burrell - Out (Illness)",
    "Minnesota Lynx": "Antonia Delaere - Out (Not Injury Related); Dorka Juhasz - Out (Not Injury Related); Elena Buenavida - Out (Coach's Decision); Liatu King - Out (Coach's Decision); Courtney Williams - Out (Lower Leg)",
    "New York Liberty": "Satou Sabally - Out (Concussion)",
    "Phoenix Mercury": "Kelsey Plum - Questionable (Lower Leg); Marta Suarez - Out (Concussion); Kyara Linskens - Out (Not Injury Related); Jovana Nogic - Out (Not Injury Related)",
    "Portland Fire": "Frieda Buhner - Out (Not Injury Related); Serah Williams - Out (Illness); Luisa Geiselsoder - Out (Personal); Sarah Ashlee Barker - Out (Knee); Sania Feagin - Out (Knee)",
    "Seattle Storm": "Natisha Hiedeman - Out (Shoulder)",
    "Toronto Tempo": "Nyara Sabally - Out (Calf); Maria Conde - Out (Not Injury Related); Zaay Green - Out (Coach's Decision); Julie Allemand - Out (Head); Marina Mabrey - Out (Hip); Aneesah Morrow - Out (Knee); Brittney Sykes - Out (Foot)"
  },
  "_updatedAt": "2026-08-27T20:55:10Z"
};
